stages:
  - publish
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'
      variables:
        DEPLOY_VARIABLE: production
        CHART_NAME: beep-app-of-apps

package-publish-helm:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - export VERSION=$CI_COMMIT_TAG
    # Echo pour débogage des variables d'environnement
    - 'echo "VERSION: $VERSION"'
    - 'echo "CHART_NAME: $CHART_NAME"'
    # Modifier la version du chart
    - 'sed "s/version: 0.1.0/version: $VERSION/g" applications/Chart.yaml'
    - helm package applications --version $VERSION --app-version $VERSION
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$CHART_NAME-$VERSION.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/$DEPLOY_VARIABLE/charts"'
  environment:
    name: $DEPLOY_VARIABLE
