stages:
  - publish
  - deploy

include:
  - local: "gitversion-ci-cd-plugin-extension.gitlab-ci.yml"

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/'
      variables:
        DEPLOY_VARIABLE: production
        CHART_NAME: beep-app-of-apps

determineversion:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TAG
  extends: .gitversion_function

package-publish-helm:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  image: alpine/helm:latest
  dependencies:
    - determineversion
  script:
    - export VERSION=$GitVersion_MajorMinorPatch
    # Echo pour débogage des variables d'environnement
    - 'echo "VERSION: $VERSION"'
    - 'echo "CHART_NAME: $CHART_NAME"'
    # Modifier le fichier values.yaml
    # Vérifier le contenu de values.yaml après modification
    - cat helm/docs/values.yaml
    - helm package helm/app-of-apps --version $VERSION --app-version $VERSION
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$CHART_NAME-$VERSION.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/$DEPLOY_VARIABLE/charts"'
  environment:
    name: $DEPLOY_VARIABLE
