apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: beep
  source:
    repoURL: "https://gitlab.polytech.umontpellier.fr/api/v4/projects/3726/packages/helm/production"
    chart: beep-app-of-apps
    targetRevision: "*"
    helm:
      valueFiles:
        - values.yaml
        - staging.yaml
  destination:
    server: "https://162.38.112.211:6443"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
