applications:
  - name: "api-staging"
    project: "beep"
    namespace: "beep-staging"
    chart: "beep-api-staging"
    destination: "https://162.38.112.211:6443"
    repoURL: "https://gitlab.polytech.umontpellier.fr/api/v4/projects/3449/packages/helm/staging"
    targetRevision: "*"
  - name: "front-staging"
    project: "beep"
    namespace: "beep-staging"
    chart: "beep-frontend-staging"
    destination: "https://162.38.112.211:6443"
    repoURL: "https://gitlab.polytech.umontpellier.fr/api/v4/projects/3427/packages/helm/staging"
    targetRevision: "*"
  - name: "front-staging"
    project: "beep"
    namespace: "beep-staging"
    chart: "beep-frontend-staging"
    destination: "https://162.38.112.211:6443"
    repoURL: "https://gitlab.polytech.umontpellier.fr/api/v4/projects/3427/packages/helm/staging"
    targetRevision: "*"
  - name: "web-rtc-staging"
    project: "beep"
    namespace: "beep-staging"
    chart: "beep-rtc-staging"
    destination: "https://162.38.112.211:6443"
    repoURL: "https://gitlab.polytech.umontpellier.fr/api/v4/projects/3511/packages/helm/staging"
