apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Project containing all production applications for argocd
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"
