{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    chart: {{ .chart }}
  destination:
    server: {{ .destination }}
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
